.........
----------------------------------------------------------------------
Ran 9 tests in 0.001s

OK
...........................
----------------------------------------------------------------------
Ran 27 tests in 0.004s

OK
...................
----------------------------------------------------------------------
Ran 19 tests in 0.001s

OK
............................
----------------------------------------------------------------------
Ran 28 tests in 0.003s

OK
.......................
----------------------------------------------------------------------
Ran 23 tests in 0.001s

OK
.F....
======================================================================
FAIL: testAtn (__main__.TestFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\tiBasic\tiBasic\tests\functionTests.py", line 59, in testAtn
    self.assertEqual(value , (2 ** 0.5) / 2)
AssertionError: 0.7853981633974483 != 0.7071067811865476

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1)
